# Generated by Selenium IDE

from selenium import webdriver
from selenium.webdriver.common.by import By


def test_search():
    driver = webdriver.Chrome()
    driver.implicitly_wait(5)
    # 打开页面：https:/www.baidu.com
    driver.get("https://www.baidu.com")
    # 输入框输入搜索内容[霍格沃兹测试学院]
    driver.find_element(By.CSS_SELECTOR, "#kw").send_keys("霍格沃兹测试学院")
    # 点击搜索按钮
    driver.find_element(By.CSS_SELECTOR, "#su").click()
    # 找到要查找的内容
    result = driver.find_element_by_css_selector(".result:nth-child(2)>h3>a>em")
    # result = driver.find_element_by_css_selector("#2>h3>a>em")
    print("result= ", result)
    assert "霍格沃兹测试学院" in result
